directive ::= 
	'A'
	| 'B'
	| 'C'
	| 'F'
	| 'H'
	| 'I'
	| 'L'
	| 'M'
	| 'P'
	| 'Q'
	| 'R'
	| 'T'
	| 'V'
	| 'X'
	| 'D'
	| 'E'
	| 'G'
	| 'N'
	| 'O'
	| 'S'
	| 'W'
	| 'Y'
	| 'ALIGN'
	| 'ASMMODE'
	| 'BOOLEVAL'
	| 'ASSERTIONS'
	| 'CALLING'
	| 'DEFINE'
	| 'ELSE'
	| 'ENDIF'
	| 'ERROR'
	| 'FATAL'
	| 'GOTO'
	| 'LONGSTRINGS'
	| 'HINT'
	| 'HINTS'
	| 'IF'
	| 'IFDEF'
	| 'IFNDEF'
	| 'IFOPT'
	| 'INFO'
	| 'INLINE'
	| 'IOCHECKS'
	| 'INCLUDE'
	| 'LINK'
	| 'LINKLIB'
	| 'TYPEINFO'
	| 'MACRO'
	| 'MAXFPUREGISTER'
	| 'MESSAGE'
	| 'MMX'
	| 'NOTE'
	| 'NOTES'
	| 'OUTPUT'
	| 'OPENSTRINGS'
	| 'PACKENUM'
	| 'PACKRECORDS'
	| 'OVERFLOWCHECKS'
	| 'RANGECHECKS'
	| 'SATURATION'
	| 'SMARTLINK'
	| 'STATIC'
	| 'STOP'
	| 'TYPEDADDRESS'
	| 'UNDEF'
	| 'VARSTRINGCHECKS'
	| 'WAIT'
	| 'WARNING'
	| 'WARNINGS'
	| 'EXTENDEDSYNTAX'
	| 'APPID'
	| 'APPNAME'
	| 'APPTYPE'
	| 'DEBUGINFO'
	| 'DESCRIPTION'
	| 'INCLUDEPATH'
	| 'LOCALSYMBOLS'
	| 'LIBRARYPATH'
	| 'MEMORY'
	| 'MODE'
	| 'OBJECTPATH'
	| 'UNITPATH'
	| 'VERSION'
	| 'STACKFRAMES'
	| 'REFERENCEINFO' 
	
%module ::= 'FreePascal'
%namespace ::= 'Cd'